# Generated by Django 3.1.1 on 2020-10-19 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glizzymail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 18, 27, 37, 692121), verbose_name='date published'),
        ),
    ]
