# Generated by Django 3.1.1 on 2020-10-20 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glizzymail', '0002_auto_20201019_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 17, 43, 16, 897799), verbose_name='date published'),
        ),
    ]
