# Generated by Django 3.1.1 on 2020-10-22 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glizzymail', '0003_auto_20201020_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 15, 14, 43, 180502), verbose_name='date published'),
        ),
    ]
